### ISSUE TITLE
Command Line interface - like in the fullnode desktop wallet

### ISSUE THREAD

**Issue by Mark76DefiChain** [saiive/saiive.live#100]
Command Line interface - like in the fullnode desktop wallet
At least for the desktop versions

**Comment by p3root** [comment]
Fullnode desktop wallet has the defi-node running in the background. 
CLI is not possible like in the fullnode wallet for the light wallet.

What is your intend on this?

**Comment by Mark76DefiChain** [comment]
My thought was, that users could use the CLI for functions that are not yet available in the GUI.
But of course that would need a running node... my bad
