### ISSUE TITLE
Can't start saiive 0.9.1335-linux in Ubuntu 21.10

### ISSUE THREAD

**Issue by eMDi101** [saiive/saiive.live#107]
How to start 0.9.1335-linux.tar.gz in Ubuntu 21.10?

**Wallet version**
0.9.1335-linux

**Describe the bug**
./saiive-live: error while loading shared libraries: libjsoncpp.so.1: cannot open shared object file: No such file or directory

**To Reproduce**
-Start Ubuntu 21.10 iso in VM and run "Try Ubuntu"
-Download + extract saiive
-chmod a+x ./saiive-live 
-run ./saiive-live 

**Environment info**
- Ubuntu 21.10

**Comment by p3root** [comment]
Update the package index:
# sudo apt-get update
Install libjsoncpp1 deb package:
# sudo apt-get install libjsoncpp1

**Comment by eMDi101** [comment]
![image](https://user-images.githubusercontent.com/26048118/143221491-70f5f0fd-6f9a-4936-8817-dde92c2e26f0.png)

**Comment by p3root** [comment]
Try it with:

sudo apt-get install -y libjsoncpp-dev

**Comment by p3root** [comment]
We want to provide the wallet within a snap package - but we havent had much time to finish it.

**Comment by eMDi101** [comment]
sounds good. then i will wait for the snap package.
if you want me to test something else, just let me know.

![image](https://user-images.githubusercontent.com/26048118/143222551-063caa63-825e-4320-8959-dc608fb9188a.png)
