### ISSUE TITLE
Auction Back button crashes app after successful bid.

### ISSUE THREAD

**Issue by webbgroup** [saiive/saiive.live#137]
**Wallet version**
latest

**Describe the bug**
app goes white on Linux platform.

**To Reproduce**
bid on an auction. 
click on the back button area.

**Expected behavior**
To go back to the main screen.

**Screenshots**
![Screenshot at 2021-12-10 09-08-31](https://user-images.githubusercontent.com/6173808/145587799-dac6bd45-37cc-4e7c-9340-5c142569f169.png)
![Screenshot at 2021-12-10 09-08-23](https://user-images.githubusercontent.com/6173808/145587800-763c4bf4-a6cb-4d80-8647-19585b88a539.png)
![Screenshot at 2021-12-10 09-08-13](https://user-images.githubusercontent.com/6173808/145587801-aa998080-048e-4d62-8b13-60df58f43816.png)

**Environment info**
 
**Smartphone (please complete the following information):**

**Additional context**

**Comment by dpfaffenbauer** [comment]
fixed in 0.16 or 0.17
