### ISSUE TITLE
DEX2 has to From fields.

### ISSUE THREAD

**Issue by webbgroup** [saiive/saiive.live#138]
**Wallet version**
Latest

**Describe the bug**
Using DEX2 causes confusion as it provides 2 From Fields in order to use it.

**To Reproduce**
Open up DEX2

**Expected behavior**
Right side field needs to say To Token:

![image](https://user-images.githubusercontent.com/6173808/145682619-42580441-1e7e-4259-9990-64ee2f13a925.png)

**Comment by p3root** [comment]
Fix with #141. Will be relased with 0.18!
