### ISSUE TITLE
Can't Payback full Loan

### ISSUE THREAD

**Issue by Shenzen1982** [saiive/saiive.live#142]
**Wallet version**
0.17.1655

**Describe the bug**
PaybackLoanTx: Cannot payback this amount of loan for PDBC, either payback full amount or less than this amount! (code 16)

**To Reproduce**
1. Click on payback loan
2. Click on max
3. Check if there are enough PDBC on the wallet. It shows 1.05 available and I have to pay back 0.059 + 0.029 interest.

**Expected behavior**
Pay full loan back.

**Screenshots**
![image](https://user-images.githubusercontent.com/41778990/145722388-6c8dc57c-cd9a-490a-be0b-992cc8f33309.png)

**Environment info**
 - Windows 365

**Comment by p3root** [comment]
This is an validation error in the blockchain. Nothing we can do about it!
https://github.com/DeFiCh/ain/issues/967
https://github.com/DeFiCh/wallet/issues/1623
