### ISSUE TITLE
HTTPS error "Unsupported protocol or cipher suite."

### ISSUE THREAD

**Issue by rnd42** [saiive/saiive.live#148]
**Wallet version**
0.19.1757

**Describe the bug**
Error when viewing "Wallet" tab in Android build:
"It seems we are having some problems with the supernode (DFI), wwe are working hard to restore our services.  Check back later..."

When I click on "Show state" it displays a HTTP browser with an error message:

"This site can't provide a secure connection

status.saiive.live uses an unsupported protocol.

ERR_SSL_VERSION_OR_CIPHER_MISMATCH"

Clicking on "Show Details" shows:

"Unsupported protocol
The client and server don't support a common SSL protocol version or cipher suite."

**To Reproduce**
Open Saiive.live Android app and if not already there go to the "Wallet" tab.

**Expected behavior**
Display my wallet status.

**Screenshots**
![Screenshot_20220110-094514](https://user-images.githubusercontent.com/618839/148805531-775b5beb-610b-4019-842a-6d8f21d96364.jpg)
![Screenshot_20220110-094518_Brave](https://user-images.githubusercontent.com/618839/148805533-3d17c797-bf3d-4f73-a7f4-ef68c4cb14d0.jpg)
![Screenshot_20220110-094523_Brave](https://user-images.githubusercontent.com/618839/148805536-4d7d0941-1255-4604-9e05-4c2b8d5e4311.jpg)

**Environment info**
 - OS: Android
 - Version 11
 
**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20 FE 5G

 - OS: Android
 - Version 11

**Additional context**
I first saw this about an hour ago, I successfully used the app yesterday around 1:30 PM (GMT -7).

**Comment by rnd42** [comment]
Yeah, Colorado.

**Comment by p3root** [comment]
Status page fixed (DNS needs some time to re-sync). Supernode for US Customers should be also up and running. need to validate first! Please feel free to re-open if not.

**Comment by rnd42** [comment]
Yup, looks good!  Thank you for the app and your attention!
