### ISSUE TITLE
Add ETH-DFI liquidity produces Bad State

### ISSUE THREAD

**Issue by ramsyman** [saiive/saiive.live#22]
**Wallet version**
0.2.0.963

**Describe the bug**
Add ETH / DEFI liquidity produces Bad State (see attachment)

**To Reproduce**

**Expected behavior**

**Screenshots**

![1AD253F1-E62F-41F6-9B10-4CE5953974B5](https://user-images.githubusercontent.com/81580071/114652281-db8fa480-9ce5-11eb-9053-e92cc8dbc853.png)

**Environment info**
 
**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: 14.4.2

**Additional context**

**Comment by p3root** [comment]
Fixed
