### ISSUE TITLE
Deduct 0.001 DFI when sending max. DFI

### ISSUE THREAD

**Issue by Mark76DefiChain** [saiive/saiive.live#76]
**Is your feature request related to a problem? Please describe.**
There are no UTXOs left after sending max DFI amount.
Before the wallet user can eg change tokens , the user needs to send some UTXOs to his wallet first

**Describe the solution you'd like**
After sending max DFI, there should be at least 0.001 UTXO left for the next transaction
the amount of available UTXOs should be decreased by 0.001 before sending them
(same behavior like the DefiChain Light Wallet) 

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by webbgroup** [comment]
Why does this need to exist? As opposed to just letting the account close out? Doesn't this promote orphaned accounts left to die? How does one 100% close out the accounts of saiive?

**Comment by webbgroup** [comment]
So what is the bare minimum to write to the blockchain then?

**Comment by webbgroup** [comment]
So why does it need to be more than enough, as opposed to the minimum to
close something out? That doesn't look like an honest application.

Saiive needs to be better than Defichain wallet rather than status quo, in
order to gain community support.

**Comment by p3root** [comment]
The suggest something better. You can't reserve only the minimun for a tx. TX fees are not set to a fixed rate - it also depends on the size of the transaction. Having a buffer is not wrong at all. 

And 1/1000 of a DFI is less then a penny.

**Comment by webbgroup** [comment]
It is less than a penny now. But DFI is expected to hit $50 #RoadTo50

So will it change within the code at that time? Or perhaps make it fixed to
the most expensive type of transaction and call it good.

**Comment by p3root** [comment]
TBH, I don't get your point. The DFI are not locked or something. You can still send 100% of your funds. But a small fraction of a UTXO coin will be reserved for DeFi Transactions.  

This will remove a lot of errors we have right now - only today I had 2 users that don't now what UTXO and account tokens are and had 0 UTXO after some transactions. You can't do any operation if you don't have any UTXO left.

**Comment by p3root** [comment]
done with 0.19. but still needs some testing!
