### ISSUE TITLE
Disable BTC Account not working

### ISSUE THREAD

**Issue by Mark76DefiChain** [saiive/saiive.live#83]
**Wallet version**
0.8.0 1234

**Describe the bug**
After Disabling  the BTC Account, it is still visible in the account list

**To Reproduce**
Disable BTC Account, save, return to account list

**Expected behavior**
BTC account not visible

**Screenshots**
![B4E9056C-934F-436F-B481-0F4F5CCD4802](https://user-images.githubusercontent.com/89530367/137262590-72e45d82-8275-417b-a26e-9c3957c32fa9.jpeg)

Environment info

OS: iOS
Version 15.0.2
Smartphone (please complete the following information):
iPhone 12 Pro Max

**Comment by p3root** [comment]
Fixed with #86
